### ISSUE TITLE
Filtering and Searching in Quarry (v2) API

### ISSUE THREAD

**Issue by mzagaja** [USDepartmentofLabor/DOLAPI#12]
Wanted to put this question I posted at http://opendata.stackexchange.com/questions/5582/filtering-and-searching-data-using-department-of-labor-quarry-api-v2 here just to make sure it is seen (not sure where the appropriate place is but it tried to create it with a "labor" tag and then denied me the ability to do so since I didn't have enough reputation so I'm concerned it won't otherwise be seen).

I am attempting to query the OSHA Inspection data from the DOL Quarry API as shown at http://developer.dol.gov/health-and-safety/dol-osha-enforcement/#osha_inspection. I have found API documentation at http://developer.dol.gov/accessing-the-apis-using-http-requests/ for data.dol.gov that indicates you can search by dates, however I would like to search by other fields like site_state or naics_code. I tried simply appending something like site_state/ct to my request and it did not filter or search. Is there anyway to do this or documentation I am missing?

**Comment by MikePulsiferDOL** [comment]
We don't yet support what appears to be the equivalent of a WHERE clause in the URL.  We've created an issue (see GitHub reference note above) to track this.

**Comment by brianworkfirst** [comment]
I'm struggling with this too. I have CuRL setup, but it's hardly practical because I have no way of either paging to the next set of 200 records and I have no way of filtering by a set of activity_nbr's or anything else except date. If it hits 200 records, then I'm out of luck for a day's worth of data for a pull. Is there an alternative besides manual pulling of this information?

**Comment by zenolee22** [comment]
I wanted to know if there were any updates on whether or not filtering would be added?
